parameters:
    fridge.firebase.generator.token_generator.class: Fridge\FirebaseBundle\Generator\TokenGenerator
    fridge.firebase.task.refresh_podcast.class: Fridge\FirebaseBundle\Task\RefreshPodcast
    fridge.firebase.consumer.read_node.class: Fridge\FirebaseBundle\Consumer\ReadNode
    fridge.firebase.client.firebase_client.class: Fridge\FirebaseBundle\Client\FirebaseClient
    fridge.firebase.command.refresh_podcast.class: Fridge\FirebaseBundle\Command\RefreshPodcast

services:
    fridge.firebase.generator.token_generator:
        class: %fridge.firebase.generator.token_generator.class%
        arguments: [%firebase_secret_key%]

    fridge.firebase.task.refresh_podcast:
        class: %fridge.firebase.task.refresh_podcast.class%
        arguments:
            - @old_sound_rabbit_mq.refresh_podcast_producer

    fridge.firebase.consumer.read_node:
        class: %fridge.firebase.consumer.read_node.class%
        arguments:
            - @fridge.firebase.client.firebase_client
            - @logger

    fridge.firebase.client.firebase_client:
        class: %fridge.firebase.client.firebase_client.class%
        arguments:
            - %firebase_base_url%
            - %firebase_secret_key%

    fridge.firebase.command.refresh_podcast:
        class: %fridge.firebase.command.refresh_podcast.class%
        arguments:
            - @fridge.firebase.task.refresh_podcast
            - @fos_user.user_manager
        tags:
            - { name: console.command }