language: php

php:
  - 5.5

before_script:

  - sudo apt-get install nginx
  - sudo apt-get install php5-fpm
  - sudo cp $TRAVIS_BUILD_DIR/vhost.template /etc/nginx/sites-enabled/fridge-subscription-demo
  - sed 's|APP_URLS|fridge-subscription-demo.local|g;s|APP_PATH|$TRAVIS_BUILD_DIR|g;s|APP_NAME|fridge-subscription-demo|g' /etc/nginx/sites-enabled/fridge-subscription-demo
  - cat /etc/nginx/sites-enabled/fridge-subscription-demo

  - sudo service nginx restart
  - sudo service php5-fpm restart

  - composer install
  - app/console doc:database:create
  - app/console doc:schema:update --force

  - sudo service nginx restart
  - sudo service php5-fpm restart


script:
  - ./bin/behat --config behat.yml

addons:
  hosts:
    - fridge-subscription-demo.local