language: php

php:
  - 5.5

before_script:

  - sudo apt-get install nginx
  - sudo add-apt-repository ppa:ondrej/php5 -y
  - sudo apt-get update
  - sudo apt-get install python-software-properties
  - sudo apt-get install php5-fpm
  - sudo apt-get install php5-cli
  - sudo apt-get install php5-curl

  - sudo cp $TRAVIS_BUILD_DIR/vhost.template /etc/nginx/sites-enabled/fridge-subscription-demo.local
  - sudo sed 's|APP_URLS|fridge-subscription-demo.local|g;s|APP_PATH|/home/travis/build/EddyLane/DemoSubscriptionBundle|g;s|APP_NAME|fridge-subscription-demo.local|g' /etc/nginx/sites-enabled/fridge-subscription-demo.local --in-place

  - composer update -n
  - app/console doc:database:create
  - app/console doc:schema:update --force
  - app/console cache:warm

  - sudo chmod -R 0777 $TRAVIS_BUILD_DIR/app/cache
  - sudo chmod -R 0777 $TRAVIS_BUILD_DIR/app/logs

  - sudo service nginx restart
  - sudo service php5-fpm restart

  - echo $TRAVIS_PHP_VERSION

script:

  - ./bin/behat --config behat.yml

addons:

  hosts:
    - fridge-subscription-demo.local
