language: php

php:
  - 5.5

before_script: composer install

services:
  - mysql
  - nginx
  - php5-fpm

before_script:

  - cp .vhost.template /etc/nginx/sites-enabled/fridge-subscription-demo
  - /etc/init.d/nginx restart

  # db setup
  - app/console doc:database:create
  - app/console doc:schema:update --force


script:
  - ./bin/behat --config behat.yml
