fridge_user_podcasts:
    resource: Fridge\PodcastBundle\Controller\PodcastController
    type:     rest
    prefix:   /

fridge_user_leaderboard:
    resource: Fridge\PodcastBundle\Controller\LeaderboardController
    type:     rest
    prefix:   /