services:

    fride.podcast.server.podcast_add_server:
        class: Fridge\PodcastBundle\Server\PodcastAddServer
        arguments:
            - @fridge.podcast.task.add_podcast
            - @logger

    fride.podcast.server.podcast_refresh_server:
        class: Fridge\PodcastBundle\Server\PodcastRefreshServer
        arguments:
            - @fridge.podcast.task.refresh_podcasts
            - @logger
            - @fridge.user.manager.user_manager

    fridge.podcast.task.abstract_task:
        class: Fridge\PodcastBundle\Task\AbstractTask
        abstract: true
        arguments:
            - @fridge.firebase.client.firebase_client
            - @fridge.api.client.google_feed
            - @fridge.api.client.itunes_search
            - @fridge.api.notification.gcm_notification
            - @jms_serializer
            - @snc_redis.default
            - @logger

    fridge.podcast.task.add_podcast:
        class: Fridge\PodcastBundle\Task\AddPodcast
        parent: fridge.podcast.task.abstract_task

    fridge.podcast.task.refresh_podcast:
        class: Fridge\PodcastBundle\Task\RefreshPodcast
        parent: fridge.podcast.task.abstract_task

    fridge.podcast.task.refresh_podcasts:
        class: Fridge\PodcastBundle\Task\RefreshPodcasts
        parent: fridge.podcast.task.abstract_task
        calls:
            - [setRefreshPodcastTask, [@fridge.podcast.task.refresh_podcast]]