imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    test: ~
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    form:
        csrf_protection:
            enabled: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"
            FRIDGESB:
                namespace_prefix: "Fridge\\SubscriptionBundle"
                path: "%kernel.root_dir%/serializer/FRIDGESB"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: oauth_authorize
    user_class: Fridge\UserBundle\Entity\User
    group:
        group_class: Fridge\UserBundle\Entity\Group

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations:  true }

fridge_subscription:
    user_class: Fridge\UserBundle\Entity\User
    stripe_sk: "%stripe_test_secret_key%"
    enable_listeners: false

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: ['accept', 'content-type']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        Fridge\ApiBundle\Entity\Client
    access_token_class:  Fridge\ApiBundle\Entity\AccessToken
    refresh_token_class: Fridge\ApiBundle\Entity\RefreshToken
    auth_code_class:     Fridge\ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            supported_scopes: user

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    body_converter:
        enabled: true
    view:
        view_response_listener: 'force'
    routing_loader:
        default_format:       json
        include_format:       false
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: false
    exception:
        codes:
            'Fridge\SubscriptionBundle\Exception\NoCardsException': 403
            'Fridge\SubscriptionBundle\Exception\FridgeCardDeclinedException': 402
            'Fridge\SubscriptionBundle\Exception\InvalidTokenException': 402
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': 403
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq_host%"
            port:     5672
            user:     "%rabbitmq_user%"
            password: "%rabbitmq_pass%"
            vhost:    "%rabbitmq_vhost%"
            lazy:     true
    producers:
        refresh_podcast:
            connection:       default
            exchange_options: { name: 'file_nodes', type: direct }
    consumers:
        refresh_podcast:
            connection:       default
            exchange_options: { name: 'file_nodes', type: direct }
            queue_options:    { name: 'file_nodes' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
            callback:         fridge.firebase.consumer.refresh_podcasts
    rpc_clients:
        podcast:
            connection: default
    rpc_servers:
        podcast:
            connection: default
            callback:   fride.podcast.server.podcast_server
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%redis_dsn%"
            logging: %kernel.debug%
        cache:
            type: predis
            alias: cache
            dsn: "%redis_dsn%"
            logging: true
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default          # the name of your entity_manager connection
            document_manager: default        # the name of your document_manager connection
        result_cache:
            client: cache
            entity_manager: [default]  # you may specify multiple entity_managers
            namespace: "dcrc:"
        query_cache:
            client: cache
            entity_manager: default

ekino_new_relic:
    enabled: %new_relic_enabled%                                             # Defaults to true
    application_name: %new_relic_name%             # default value in newrelic is "PHP Application", or whatever is set
    api_key: %new_relic_api_key%                  # New Relic API
    license_key: %new_relic_license_key%                      # New Relic license key
    xmit: false                           # if you want to record the metric data up to the point newrelic_set_appname is called, set this to true
    logging: true                         # If true, logs all New Relic interactions to the Symfony log
    instrument: false                     # If true, uses enhanced New Relic RUM instrumentation (see below)
    log_exceptions: true                  # If true, sends exceptions to New Relic
    log_commands: true                    # If true, logs CLI commands to New Relic as Background jobs (>2.3 only)
    using_symfony_cache: false            # Symfony HTTP cache (see below)
    transaction_naming: route             # route, controller or service (see below)
    transaction_naming_service: ~         # Transaction naming service (see below)
    ignored_routes: []                    # No transaction recorded for this routes
    ignored_paths: []                     # No transaction recorded for this paths
    ignored_commands: []                  # No transaction recorded for this commands (background tasks)