imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: debug
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console

fridge_firebase:
    firebase_base_url: '%firebase_base_url%'

fridge_api:
    google_feed_url: '%google_feed_api_url%'
    itunes_search_url: '%itunes_search_url%'