fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login_oauth:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: FOSUserBundle:Security:login }


fridge_subscription_routing:
    resource: "@FridgeSubscriptionBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api/v1/

fridge_user_routing:
    resource: "@FridgeUserBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api/v1/

login_check_new:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: FOSUserBundle:Security:check, _format: json }
    methods: [POST]
    requirements:
        _format:  json

api:
    resource: "@FridgeApiBundle/Controller"
    prefix: /api/v1/
    type:     annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"