fridge_subscription_routing:
    resource: "@FridgeSubscriptionBundle/Resources/config/routing.yml"
    type: rest

fridge_user_routing:
    resource: "@FridgeUserBundle/Resources/config/routing.yml"
    type: rest

login_check:
    path: /security/login
    defaults: { _controller: FOSUserBundle:Security:check, _format: json }
    methods: [POST]
    requirements:
        _format:  json