fridge_demo_users:
    resource: Fridge\UserBundle\Controller\UserController
    type:     rest
    prefix:   /

fridge_demo_subscriptions:
    resource: Fridge\UserBundle\Controller\SubscriptionController
    type:     rest
    prefix:   /

fridge_demo_users_cards:
    resource: Fridge\UserBundle\Controller\UserCardController
    parent:   fridge_demo_users
    type:     rest
    prefix:   /