parameters:
    fridge.api.client.gcm_client.class: Fridge\ApiBundle\Client\GCMClient
    fridge.api.notification.gcm_notification.class: Fridge\ApiBundle\Notification\GCMNotification

services:
    fridge.api.client.gcm_client:
        class: %fridge.api.client.gcm_client.class%
        arguments:
            - @logger
            - %gcm_url%
            - %gcm_api_key%

    fridge.api.notification.gcm_notification:
        class: %fridge.api.notification.gcm_notification.class%
        arguments:
            - @fridge.api.client.gcm_client