parameters:
    fridge.api.client.gcm_client.class: Fridge\ApiBundle\Client\GCMClient
    fridge.api.notification.gcm_notification.class: Fridge\ApiBundle\Notification\GCMNotification
    fridge.api.client.google_feed.class: Fridge\ApiBundle\Client\GoogleFeedClient

services:
    fridge.api.client.gcm_client:
        class: %fridge.api.client.gcm_client.class%
        arguments:
            - @logger
            - %gcm_url%
            - %gcm_api_key%

    fridge.api.client.google_feed:
        class: %fridge.api.client.google_feed.class%
        arguments:
            - @logger
            - %fridge_api.google_feed_url%

    fridge.api.notification.gcm_notification:
        class: %fridge.api.notification.gcm_notification.class%
        arguments:
            - @fridge.api.client.gcm_client