parameters:
#    fridge_podcast_search.example.class: Fridge\PodcastSearchBundle\Example

services:
#    fridge_podcast_search.example:
#        class: %fridge_podcast_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
